all:
	g++ Grid.cpp UniformGrid.cpp ScalarAttributes.cpp VectorAttributes.cpp ColormapRenderer.cpp StreamlineRenderer.cpp main.cpp GlyphRenderer.cpp  -std=c++0x -D__LINUX_COMPILE -o assignment2 -lGL -lglut -lGLU
