LIBS = -lGL -lGLU -lglut

all:
	g++ *.cpp -g -std=c++0x -D__LINUX_COMPILE -o sand -lGL -lglut -lGLU -L/home/akshay/Advanced\ Computer\ Graphics/pngwriter/build/lib `freetype-config --cflags` -I/usr/local/include  -L/usr/local/lib -lpng -lpngwriter -lz -lfreetype
